### ISSUE TITLE
requesting dying light 1 enhanced v1.35 (03991)

### ISSUE THREAD

**Issue by sfhdfshdfh** [GoldHEN/GoldHEN_Cheat_Repository#179]
does anyone have the json or other cheats for this. 
dl1 enhanced v1.35
03991
latest i see in the list is 1.31

thanks.

**Comment by kmeps4** [comment]
I've added CUSA03991 v01.35.
Please Test it and let me know.

**Comment by kmeps4** [comment]
I'm gonna close since this is a request and not a bug
