### ISSUE TITLE
CUSA14168 resident evil 3 v1.05

### ISSUE THREAD

**Issue by LeQiu77** [GoldHEN/GoldHEN_Cheat_Repository#183]
latest cheat not showing on cheat manager.i already check and there is jsn file for this region and version on data/goldhen/jsn folder.

**Comment by kmeps4** [comment]
I've verified and cheat in indeed on Repository. How do you upload Cheats to your PS4?

**Comment by LeQiu77** [comment]
sorry for late reply.i dont open gmail often.normally i load the cheat with
goldhen cheat manager by pressing the option button on ds4.
