### ISSUE TITLE
Elden Ring CUSA28863_01.05.json typo

### ISSUE THREAD

**Issue by edmaren** [GoldHEN/GoldHEN_Cheat_Repository#188]
Can anyone change this in file? "version" shows "1.05" instead of "01.05", so GoldHEN Cheat Manager doesn't detect the game.

Thank you.

**Comment by kmeps4** [comment]
Which GoldHEN version are you using? Cheats are loaded by Name and process that's the why we need to have a proper naming on files... so the version "typo" will load without issues.. Anyways I've renamed it to 01.05
