### ISSUE TITLE
Requesting Earth Defense Force 5 CUSA12504_01.01

### ISSUE THREAD

**Issue by Contra49628** [GoldHEN/GoldHEN_Cheat_Repository#190]
Hello! I need these cheats for some crazy fun with friends.

"Molly" or anybody help me!😁

Godmode (Mechs/Vehicles)
Godmode (Player 1)
Godmode (Player 2)
Infinite Ammo
Rapid Fire
Unlock Every Weapon
Max All Weapon Star Level

**Comment by kmeps4** [comment]
Try to ask on PS4 Trainer Team Discord or Team Reaper Discord please.
On GoldHEN organization we dont develop cheats..

**Comment by kmeps4** [comment]
I'm gonna close this one since this is not a issue
