### ISSUE TITLE
Add Uncharted Collection Cheats

### ISSUE THREAD

**Issue by Contra49628** [GoldHEN/GoldHEN_Cheat_Repository#197]
Uncharted The Nathan Drake Collection - GoldHen Cheats

CUSA02320 - json; shn v01.02 
CUSA02343 - json; shn v01.02 
CUSA02344 - json; shn v01.02 
CUSA02826 - json; shn v01.02 

*Uncharted Drake's Fortune
-Infinite Ammo/No Reload
-Enable Dev Menu
-No FPS On Screen

*Uncharted 2 Among Thieves
-Enable Dev Menu
-No FPS On Screen

*Uncharted 3 Drakes Deception
-Enable Dev Menu
-No FPS On Screen

*** Note: For all Uncharted series, to navigate the "Dev Menu", press:

               L3 + upper left TouchPad = Menu 1 in
               Upper left TouchPad only = Menu 1 out.
               L3 + upper right TouchPad = Menu 2 in
               Upper right TouchPad only = Menu 2 out
               D-Pad To Navigate
               X To Turn On/Off Option
               Square To Previous Menu
               Circle For "+" Option
               L1 + R1 for Levitation Mode
               L2 = Up, R2 = Down (In Levitate Mode)

[Uncharted Collection Cheats.zip](https://github.com/GoldHEN/GoldHEN_Cheat_Repository/files/11849221/Uncharted.Collection.Cheats.zip)

**Comment by kmeps4** [comment]
Cheats have been added
