### ISSUE TITLE
Cheat RESIDENT EVIL 2 CUSA09193 

### ISSUE THREAD

**Issue by subzero327** [GoldHEN/GoldHEN_Cheat_Repository#199]
Hello friends, it is necessary to add the cheats for this game, most of us have the USA version in v1.05 and we find that there are no cheats, I would appreciate it very much

**Comment by Contra49628** [comment]
> Hello friends, it is necessary to add the cheats for this game, most of us have the USA version in v1.05 and we find that there are no cheats, I would appreciate it very much

The CUSA09193 v1.06 json cheat is available.

Install the 01.06 update. If it reports an error, install it with the included base.pkg.

**Comment by kmeps4** [comment]
@subzero327 I've added CUSA09193_01.05.. please test it.
