### ISSUE TITLE
Request Cheats

### ISSUE THREAD

**Issue by KaiserLiebert** [GoldHEN/GoldHEN_Cheat_Repository#210]
Hello, can u guys make a cheat for F1 Manager 2022
Version : 1.12
- Money per Reseach/Design (100 Million)
- Infinite Windtunnel Hours
- Infinite CFD Hours
- Max Development Points (on usage)
- Infinite ERS Recharge (player)
- Min 4kg fuel (player)
- Perfect Tire Condition (player)
- Max Skill with one development point

**Comment by bucanero** [comment]
https://github.com/GoldHEN/GoldHEN_Cheat_Repository/discussions/42

**Comment by Chokenz1007** [comment]
Hello can u make cheats on borderlands THC CUSA01401 – USA (v1.08)
