### ISSUE TITLE
CUSA19515

### ISSUE THREAD

**Issue by Lutr0nix** [GoldHEN/GoldHEN_Cheat_Repository#239]
Hello, i am having a problem with the cheats for this game (v01.03).
I don't know if the problem only comes from me, the fact remains that the game crash every time i put Infinite Ammo (or Infinite Health don't work) for example. Ciao

nb: sorry if i'm not in the right place

**Comment by kmeps4** [comment]
Please visit following link: https://github.com/GoldHEN/GoldHEN_Cheat_Repository/discussions/42
