### ISSUE TITLE
FF7R (CUSA07211/07187) various problems

### ISSUE THREAD

**Issue by subworx** [GoldHEN/GoldHEN_Cheat_Repository#24]
Hi,

The cheats for CUSA07211 (US) v1.01 do not work in US/EU 1.01 version. Mostly tried Inf HP/MP/ATB, but the others didn't work either.
They work on CUSA07211 (US) v1.00 **and** CUSA07187 (EU) v1.00 though.

One cheat is broken on US v1.00 as well as v1.01: "Easy Squat | x99 per Squat" on 1.00 freezes both Cloud's and the opponent's squats at 1 instead of giving high numbers, on 1.01 it simply does nothing.

Thanks and regards.

**Comment by kmeps4** [comment]
thx for the report. I'll check it soon.
