### ISSUE TITLE
Cyberpunk 2077 1.31

### ISSUE THREAD

**Issue by dharz20** [GoldHEN/GoldHEN_Cheat_Repository#25]
When i open the cheats it gave me kernel panic

**Comment by faridalgeria** [comment]
Hello..why there isnt cyberpunk2077 cusa18278 v1.31 cheats code in the list ? And Thank for all your effort.

**Comment by kmeps4** [comment]
Hello.. let me confirm why this one is having KP. will answer again soon

**Comment by Fall0n** [comment]
> Hello.. let me confirm why this one is having KP. will answer again soon

Any news why it have KP?

**Comment by dharz20** [comment]
Sorry been busy. It works but after 3rd time it gave me another kp

**Comment by kmeps4** [comment]
seems Cyberpunk cheats are not compatible... need to verify

**Comment by faridalgeria** [comment]
Thnks
