### ISSUE TITLE
can't activate cheats cusa01341_07

### ISSUE THREAD

**Issue by sander9912** [GoldHEN/GoldHEN_Cheat_Repository#28]
I can see the cheats but or i try to activate it, there is no message coming up that the cheat is activated.

It is the only game so far i know what give the problem.

**edit:** i think the problem is "hint":null in the json file.

**Comment by kmeps4** [comment]
Hello thx for the report. will verify it

**Comment by kmeps4** [comment]
Hello.
Can you try this one and let me know if working now:
https://anonfiles.com/30BbB7aeyf/CUSA01341_01.07_json
and yes if a offset is not absolute the parser will not process correctly the cheat if "hint":null is there

**Comment by sander9912** [comment]
it works now perfectly.

**Comment by kmeps4** [comment]
Thx for Feedback.
