### ISSUE TITLE
Contra Operation Galuga

### ISSUE THREAD

**Issue by cooldroid** [GoldHEN/GoldHEN_Cheat_Repository#328]
Contra Operation Galuga - Max Credits cheat changed my credits to negative infinite. This is not good. How get my credits back?

**Comment by Tribb** [comment]
can you be a bit more specific as we have 2 versions circulating

**Comment by cooldroid** [comment]
@Tribb - I am using the version in this commit: https://github.com/GoldHEN/GoldHEN_Cheat_Repository/commit/e9b63f455aba8c81469c7c65e08ffb4ea38ce88d#diff-eeb10b0aa9f6160989f92663cf92e1b0f1c2d351a464eb9b4c1946ff9ad6a834

I am not sure about the other version. Where can I find it?

**Comment by cooldroid** [comment]
@Tribb - were you able to validate the issue?

**Comment by Tribb** [comment]
no mate Ali-mk is using it now and had no probs so cant help you fix it, You can come to the discord server and ask him yourself

**Comment by cooldroid** [comment]
Can you please share the Discord link?

**Comment by NOBLE186** [comment]
Same issue , Change my credit to negative. The only way to get around it is by deleting the save data and start a new game without triggering the cheat.

**Comment by Tribb** [comment]
Ok Ive deleted the Cheat and uploaded a new one please make sure you delete the old one
https://discord.com/invite/pR5NTEVBGt
Sorry about that guys I hope the new one is ok

**Comment by cooldroid** [comment]
@Tribb - Thanks a lot, this new cheat works well.
