### ISSUE TITLE
Create a offline Ultimate version for FC24, just like the Zhm86 patch for Other cods

### ISSUE THREAD

**Issue by rickwrimes** [GoldHEN/GoldHEN_Cheat_Repository#350]
FC24 offline unlock all!

newest version

Willing to test, Discord: rickwrimes

**Comment by kmeps4** [comment]
Don't open an issue on the repo to ask for a cheat. Go to discussion

**Comment by kmeps4** [comment]
https://github.com/GoldHEN/GoldHEN_Cheat_Repository/discussions/42
