### ISSUE TITLE
Call of duty infinite warfare cheats not working  CUSA04762_01.25

### ISSUE THREAD

**Issue by aqwsdfaefgdergswerf213** [GoldHEN/GoldHEN_Cheat_Repository#355]
The cheats like god mode and 1 hit kill and inf throwables dont work

**Comment by aqwsdfaefgdergswerf213** [comment]
PLEASE FIX THIS I NEED ZOMBIES GOD MODE PLZ

**Comment by Tribb** [comment]
we dont fix only delete you will have to chase up the cheat maker for fixes

**Comment by kmeps4** [comment]
Understood. User must report to cheat developer!! Closing issue
