### ISSUE TITLE
DMC3 Cheats are not working

### ISSUE THREAD

**Issue by SukhiAaron** [GoldHEN/GoldHEN_Cheat_Repository#358]
In Devil May Cry HD Collection both DMC1 and DMC2 Cheats are working just fine except for DMC3 only infinite red orb cheat is working nothing else

**Comment by Tribb** [comment]
If you want a fix please ask the cheat maker all we do is delete non working cheats and as this is 80% working it will be left in the Db

**Comment by kmeps4** [comment]
Understood. User must report to cheat developer!! Closing issue
