### ISSUE TITLE
Resident Evil Revelations 2 CUSA00924 v 1.05 cheats don't work

### ISSUE THREAD

**Issue by AlterArcher00** [GoldHEN/GoldHEN_Cheat_Repository#402]
Resident Evil Revelations 2 CUSA00924 v 1.05 crashes when cheats are applied and character shoots or gets hit

**Comment by neo305** [comment]
What version of goldhen are you using?

**Comment by AlterArcher00** [comment]
goldhen 2.4b17.3

**Comment by neo305** [comment]
The 2.4b17.2 and see if you get same results.

**Comment by AlterArcher00** [comment]
I already tried but it keeps crashing

**Comment by Tribb** [comment]
just updated this game with new cheats from Dioniso should be merged soon let us know if this one is working for you please

> Author

**Comment by AlterArcher00** [comment]
I've been trying, some cheats work but the raid mode ones crash the game

**Comment by kmeps4** [comment]
in that case you will have to report to original Author!!! Shoud we close and delete the Cheat? @Tribb ?

**Comment by Tribb** [comment]
@kmeps4 raid mode is a small part of the game so no need to delete just report it to the author @AlterArcher00 sorry about that. just report the broken ones to the author please

**Comment by kmeps4** [comment]
ok so should we delete that specific raid mode?

**Comment by Tribb** [comment]
im on this game now ill delete the non working and upload a fixed one soon you can close this

**Comment by kmeps4** [comment]
Ok thx a lot

**Comment by Tribb** [comment]
new file updated all cheats should be now fixed
