### ISSUE TITLE
Naming convention documentation does not mention including the .elf filename as needed.

### ISSUE THREAD

**Issue by michaelcasson** [GoldHEN/GoldHEN_Cheat_Repository#44]
When making a cheat file for Assassin's Creed: The Ezio Collection, I struggled to get my finished cheat file to be recognized in GoldHEN.  Being a collection of three games in one, it works a bit differently than most. I eventually discovered that you must append the specific .elf filename you're targeting in the cheat filename itself. Example: 'CUSA05008_01.00_ScimitarAC2.elf.json'

Without this, the cheat file would be recognized at the first main screen, but disappear/not work once one of the individual games were chosen.

The only reason I discovered this is because I saw some of the other files named this way and eventually tried it. I assumed it was just for organizational sake and not really used by the cheat engine since the .elf file is specified inside the JSON itself under 'process' and it is not documented anywhere, including the 'naming convention' section.

A quick addition to the readme would likely be helpful for others.

**Comment by kmeps4** [comment]
Hello. You're correct I'll edit the instructions file.
I'll close this one since it's not a issue or bug.
Thanks a lot for submission.
