### ISSUE TITLE
CUSA28561 HFW not working

### ISSUE THREAD

**Issue by ashraf008** [GoldHEN/GoldHEN_Cheat_Repository#45]
The updated Horizon forbidden west cheats doesn't seems to work on v1.17 ps4 pro 9.0. The earlier cheats were working just fine for the same game,

**Comment by kmeps4** [comment]
ok thx for letting us know.. I'll check it and update them..!!

**Comment by kmeps4** [comment]
https://github.com/GoldHEN/GoldHEN_Cheat_Repository/discussions/42#discussion-4222094

**Comment by megacm585simplelogin** [comment]
Infinite health (Need MC) doesn't work even after activating MC. Please guide.
