### ISSUE TITLE
Remove cheat celogamez for HFW 1.17

### ISSUE THREAD

**Issue by ankorez** [GoldHEN/GoldHEN_Cheat_Repository#52]
Hello thanks for awesome work
Please Can you remove the cheat from celogamez on HFW 1.17 theses cheats dosen't work and there are another but we cannot select them because there are theses shit of celogamez
Thanks you very much

**Comment by ankorez** [comment]
Yes
That's not crash but it dosen't work. 
Infinite Health/1 Hit Kill (Master Code)
1 Hit Kill (Need MC)
Infinite Health (Need MC)
For CUSA28561 and cheat from celogamez
I try to enable these 3 cheats in game but thats not work and i don't find any informations on what is Master Code
There are another cheat from another guy available without master code for the same game and same région but the multi cheat for same game is not available yet
Thanks

**Comment by kmeps4** [comment]
Ok can you go please to the following Discussion: https://github.com/GoldHEN/GoldHEN_Cheat_Repository/discussions/42
