### ISSUE TITLE
Error cheats

### ISSUE THREAD

**Issue by Hasssan13** [GoldHEN/GoldHEN_Cheat_Repository#57]
Hello, the cheats of dragon quest XI are not good cause v 1.01 doesn't exist and also the v 1.02. There are only the version 1.00 soo you hare to fix please. Second things the cheats for final fantasy x /x-2 doesn't start they appear only in the first menu when we can chose if X or X-2 and then when we chose the game they disappear and they say that the version of the game there are no cheats

**Comment by kmeps4** [comment]
As I said.. GoldHEN 2.2.2 differs from GoldHEN 2.2.4 in the Cheat version detection. GoldHEN 2.2.4 will look for the correct cheat version.. so in this case.. I can help yoo out.. please send me the CUSA and version you need to be uploaded please to be used with latest GoldHEN.

**Comment by kmeps4** [comment]
Please continue on the following discussion: https://github.com/GoldHEN/GoldHEN_Cheat_Repository/discussions/42
