### ISSUE TITLE
 a recommendation

### ISSUE THREAD

**Issue by 44daniel** [GoldHEN/GoldHEN_Cheat_Repository#58]
hello bucanero;;;;
could add cheat for ps2, please

**Comment by bucanero** [comment]
moving this request to the cheat repository.

**Comment by kmeps4** [comment]
We already have PS2 Cheat Support.. there are several PS2 Game cheats on the repository.
https://github.com/GoldHEN/GoldHEN_Cheat_Repository

**Comment by kmeps4** [comment]
and just in case if you need to request for a special cheat please check the following discussion: https://github.com/GoldHEN/GoldHEN_Cheat_Repository/discussions/42
