### ISSUE TITLE
[Add cheats]

### ISSUE THREAD

**Issue by JNoel89** [GoldHEN/GoldHEN_Cheat_Repository#6]
### Game name

How to Survive Storm Warning Edition

### Title ID

CUSA00706

### Game Version

ex. 1.02

### Cheats JSON data

```json
{"example":"Paste JSON cheat file content"}
```

**Comment by bucanero** [comment]
@JNoel89 if you want to request cheats, use the Discussion link: https://github.com/GoldHEN/GoldHEN_Cheat_Repository/discussions/categories/cheat-requests
