### ISSUE TITLE
incompatibilidad goldhen goldhen cheats manager

### ISSUE THREAD

**Issue by bombardeo38** [GoldHEN/GoldHEN_Cheat_Repository#60]
de momento te agradezco tus aportes y tu tiempo lo segundo es que abri un reporte por un fallo que sucede que yo sepa en 2 juegos no e probado en mas uno es el cusa18534 v5.10 y el cusa02747 v1.05 apesar de tener trucos pulsando el boton share los trucos no se activan puesto que goldhen cheats manager no los reconoce con la estrella a la izquierda no se si sera del gold hen o del goldhen cheats manager te adjunto imagenes y video si puedo el video dice ser mas grande y no puedo mando fotos pero si utilizo el trainer con el movil los mismos trucos funcionan
![20220920_163359](https://user-images.githubusercontent.com/92440196/191606563-d404a6ca-e30a-4f29-b184-c5931b411e8c.jpg)
![20220920_132738](https://user-images.githubusercontent.com/92440196/191606570-5286f86c-7865-47f2-8598-edd6ae808ae9.jpg)
![20220920_132639](https://user-images.githubusercontent.com/92440196/191606575-3e9684fd-8ab9-45e1-9f79-251568164495.jpg)
![20220920_132524](https://user-images.githubusercontent.com/92440196/191606580-9cdc8899-a27f-49f1-9725-51351a3c5119.jpg)
![20220731_181048](https://user-images.githubusercontent.com/92440196/191606582-f893acd3-bf68-4ddd-b7ce-7b61072c84c2.jpg)
![20220920_132514](https://user-images.githubusercontent.com/92440196/191606588-9995e094-abf4-4550-b092-78fa8a8d701e.jpg)

**Comment by kmeps4** [comment]
Este reporte se esta viendo en el siguiente link:
https://github.com/GoldHEN/GoldHEN_Cheat_Repository/issues/59
