### ISSUE TITLE
HFW : CUSA28561 v1.17 working json cheat file 

### ISSUE THREAD

**Issue by ashraf008** [GoldHEN/GoldHEN_Cheat_Repository#62]
[CUSA28561_01.17.json.zip](https://github.com/GoldHEN/GoldHEN_Cheat_Repository/files/9640231/CUSA28561_01.17.json.zip)

Download unarchive and transfer to json folder and enjoy

**Comment by kmeps4** [comment]
Thx.. I'll check and if correct will upload

**Comment by kmeps4** [comment]
Cheat file has been uploaded to the Json repository. Thx a lot
