### ISSUE TITLE
[Add cheats]

### ISSUE THREAD

**Issue by juandavid3928** [GoldHEN/GoldHEN_Cheat_Repository#69]
### Game name

God of War Ragnarok PS4

### Title ID

CUSA34390 y CUSA34384

### Game Version

v2.00

### Cheats JSON data

```json
{"example":"Paste JSON cheat file content"}
```

### Zip link

https://www.mediafire.com/file/t5n2daploe9p5wm/WANDER.zip/file

**Comment by kmeps4** [comment]
Hello GOW Ragnarok cheas are already on the repo.
Thx.

**Comment by angelsky11** [comment]
After update cheats database online. can’t find any cheats for cusa34384. Please help to solve this problem thx
